# Generated by Django 5.2.8 on 2025-11-24 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anotif', '0001_initial'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='interactions',
            field=models.ManyToManyField(related_name='notif_comment_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='notif_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif',
            name='interactions',
            field=models.ManyToManyField(related_name='notif_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif',
            name='likes',
            field=models.ManyToManyField(related_name='notif_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_name', to='api.communitydirectory'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_comments', to='anotif.notif'),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='poll_data', serialize=False, to='anotif.notif')),
                ('update_type', models.CharField(default='Poll', max_length=50)),
                ('title', models.CharField(help_text='Poll title', max_length=200)),
                ('poll_question', models.TextField(help_text='The main poll question')),
                ('poll_type', models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='single', help_text='Type of poll voting', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('sports', 'Sports'), ('technology', 'Technology'), ('politics', 'Politics'), ('business', 'Business'), ('health', 'Health'), ('lifestyle', 'Lifestyle')], default='general', help_text='Poll category', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], default='public', help_text='Who can see and vote on this poll', max_length=20)),
                ('poll_sections', models.JSONField(default=list, help_text='Poll sections with items and colors')),
                ('images', models.JSONField(default=list, help_text='List of poll images (base64 encoded or URLs)')),
                ('settings', models.JSONField(default=dict, help_text='Poll settings and configuration')),
                ('duration_hours', models.PositiveIntegerField(default=24, help_text='Poll duration in hours')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the poll expires', null=True)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_voters', models.PositiveIntegerField(default=0)),
                ('unique_voter_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expired', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_multiple_votes', models.BooleanField(default=False)),
                ('anonymous_voting', models.BooleanField(default=False)),
                ('hide_results_until_expired', models.BooleanField(default=False)),
                ('show_results_after_vote', models.BooleanField(default=True)),
                ('send_reminders', models.BooleanField(default=True)),
                ('reminder_frequency_hours', models.PositiveIntegerField(default=12)),
                ('tags', models.JSONField(default=list, help_text='Poll tags for search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='anotif_poll_expires_31827b_idx'), models.Index(fields=['is_active', 'expired'], name='anotif_poll_is_acti_3c3584_idx'), models.Index(fields=['category'], name='anotif_poll_categor_2688e8_idx'), models.Index(fields=['visibility'], name='anotif_poll_visibil_34aaba_idx')],
            },
        ),
    ]
