# Generated by Django 5.0.6 on 2025-09-02 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auserpost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('message', 'Message'), ('blog', 'Blog'), ('user_post', 'User Post'), ('service_post', 'Service Post'), ('accommodation', 'Accommodation')], max_length=20)),
                ('description', models.TextField()),
                ('related_id', models.PositiveIntegerField()),
                ('is_read', models.BooleanField(default=False)),
                ('content_type', models.CharField(max_length=50)),
                ('extra_data', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_user_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_user_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Notif_user_post_commented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('red', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auserpost_who_commented', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auserpost_commented', to='auserpost.post')),
            ],
        ),
        migrations.CreateModel(
            name='Notif_user_post_liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('red', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auserpost_who_liked', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auserpost_liked', to='auserpost.post')),
            ],
        ),
    ]
