# Generated by Django 5.0.6 on 2025-10-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quercus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quercusmessage',
            name='completion_tokens',
            field=models.IntegerField(default=0, help_text='Tokens in the completion'),
        ),
        migrations.AddField(
            model_name='quercusmessage',
            name='finish_reason',
            field=models.CharField(blank=True, help_text='Reason generation finished', max_length=50),
        ),
        migrations.AddField(
            model_name='quercusmessage',
            name='generation_config',
            field=models.JSONField(blank=True, default=dict, help_text='Generation parameters used'),
        ),
        migrations.AddField(
            model_name='quercusmessage',
            name='model_used',
            field=models.CharField(default='gemini-pro', help_text='Gemini model used for generation', max_length=50),
        ),
        migrations.AddField(
            model_name='quercusmessage',
            name='prompt_tokens',
            field=models.IntegerField(default=0, help_text='Tokens in the prompt'),
        ),
        migrations.AddField(
            model_name='quercusmessage',
            name='response_time_ms',
            field=models.IntegerField(default=0, help_text='Response time in milliseconds'),
        ),
        migrations.AddField(
            model_name='quercusmessage',
            name='safety_ratings',
            field=models.JSONField(blank=True, default=list, help_text='Gemini safety ratings'),
        ),
        migrations.AddField(
            model_name='quercusmessage',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Approximate tokens consumed'),
        ),
        migrations.AddField(
            model_name='quercusmessage',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used'),
        ),
        migrations.AddIndex(
            model_name='quercusmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='quercus_que_convers_443b12_idx'),
        ),
        migrations.AddIndex(
            model_name='quercusmessage',
            index=models.Index(fields=['model_used', 'timestamp'], name='quercus_que_model_u_57edad_idx'),
        ),
        migrations.AddIndex(
            model_name='quercusmessage',
            index=models.Index(fields=['is_user', 'timestamp'], name='quercus_que_is_user_6db838_idx'),
        ),
    ]
