# Generated by Django 5.0.6 on 2025-09-02 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anotif', '0001_initial'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='interactions',
            field=models.ManyToManyField(related_name='notif_comment_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='notif_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif',
            name='interactions',
            field=models.ManyToManyField(related_name='notif_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif',
            name='likes',
            field=models.ManyToManyField(related_name='notif_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notif',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_name', to='api.communitydirectory'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_comments', to='anotif.notif'),
        ),
    ]
