# Generated by Django 5.0.6 on 2025-09-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotif', '0003_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='update_type',
            field=models.CharField(default='Poll', max_length=50),
        ),
    ]
