# Generated by Django 5.0.6 on 2025-09-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotif', '0004_poll_update_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='images',
            field=models.JSONField(default=list, help_text='List of poll images (base64 encoded or URLs)'),
        ),
    ]
