/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const Colors = {
  light: {
    liveScreen: {
      LessonsScreen: {
        Ongoing: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textgreen: "#00c410",
          textYellow: "#FCC500",
          textFadeYellow: "#806403", 
          textEmail: "#0D99FF",
          borderColor: "#115368",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          BackgroundSection: "#fff",
          ViewBackground: "#acf2fda6",
        },
        OnSet: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#68707688",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconGray: "#5a5a5b",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          BackgroundSection: "#fff",
          ViewBackground: "#d0d0d0a1",
        },
        FloatView: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textgreen: "#04a811",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          FloatTopViewName: "#fff",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          FloatTopViewIcon: "#115368",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          LiveScreenPostBackgroundSection: "#fff",
          LiveScreenPostBackground: "#c5c5c5",
        },
      },
      InClassesScreen: {
        Ongoing: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textgreen: "#04a811",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          BackgroundSection: "#fff",
          ViewBackground: "#acf2fda6",
        },
        OnSet: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textgreen: "#04a811",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconGray: "#5a5a5b",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          BackgroundSection: "#fff",
          ViewBackground: "#d0d0d0a1",
        },
        FloatView: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textgreen: "#04a811",
          textRed: "#ff3636",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          FloatTopViewName: "#fff",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          FloatTopViewIcon: "#115368",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          LiveScreenPostBackgroundSection: "#fff",
          LiveScreenPostBackground: "#c5c5c5",
        },
      },
      EventsScreen: {
        Ongoing: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          FloatTopViewName: "#fff",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          FloatTopViewIcon: "#115368",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          LiveScreenPostBackgroundSection: "#fff",
          LiveScreenPostBackground: "#c5c5c5",
        },
        OnSet: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          FloatTopViewName: "#fff",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          FloatTopViewIcon: "#115368",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          LiveScreenPostBackgroundSection: "#fff",
          LiveScreenPostBackground: "#c5c5c5",
        },
        FloatView: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          FloatTopViewName: "#fff",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          FloatTopViewIcon: "#115368",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          LiveScreenPostBackgroundSection: "#fff",
          LiveScreenPostBackground: "#c5c5c5",
        },
      },
      ExamsScreen: {
        Ongoing: {
          text: "#404040",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textgreen: "#00c410",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          BackgroundSection: "#fff",
          ViewBackground: "#acf2fda6",
        },
        OnSet: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconGray: "#5a5a5b",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          BackgroundSection: "#fff",
          ViewBackground: "#d0d0d0a1",
        },
        FloatView: {
          text: "#11181C",
          Fadetext: "rgba(175, 196, 200, 0.95)",
          lightText: "#5a5a5b",
          textRed: "#ff3636",
          textgreen: "#04a811",
          textYellow: "#FCC500",
          textFadeYellow: "#806403",
          textEmail: "#0D99FF",
          borderColor: "#115368",
          FloatTopViewName: "#fff",
          background: "#fff",
          tint: tintColorLight,
          icon: "#687076",
          iconRed: "#ff3636",
          FloatTopViewIcon: "#115368",
          tabIconDefault: "#687076",
          tabIconSelected: tintColorLight,
          calendar: "lightgrey",
          LiveScreenPostBackgroundSection: "#fff",
          LiveScreenPostBackground: "#c5c5c5",
        },
      },
    },
  },
  dark: {
    GlobalColors: {
      text: "#ECEDEE",
      background: "#151718",
      tint: tintColorDark,
      icon: "#9BA1A6",
      tabIconDefault: "#9BA1A6",
      tabIconSelected: tintColorDark,
      BottomTab: {
        iconOnFocus: "#057d8c",
        iconDefault: "#c5c5c5",
        borderTopColor: "#d0d0d0",
        BackgroundColor: "#fff",
      },
    },
  },
};
