# Generated by Django 5.2.8 on 2025-11-24 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuercusCampusResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('study_spot', 'Study Spot'), ('dining', 'Dining'), ('library', 'Library'), ('event_venue', 'Event Venue'), ('service', 'Service'), ('facility', 'Facility')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('building', models.CharField(blank=True, max_length=255)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuercusCareerGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=255)),
                ('interests', models.TextField()),
                ('guidance_data', models.JSONField()),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quercus_career_guidance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuercusConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quercus_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuercusPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('category', models.CharField(default='general', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quercus_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuercusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_style', models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed'), ('conversational', 'Conversational')], default='concise', max_length=50)),
                ('auto_save', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('study_reminders', models.BooleanField(default=True)),
                ('campus_updates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quercus_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuercusStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('duration_weeks', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('plan_data', models.JSONField()),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quercus_study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuercusAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_queries', models.IntegerField(default=0)),
                ('study_queries', models.IntegerField(default=0)),
                ('schedule_queries', models.IntegerField(default=0)),
                ('campus_queries', models.IntegerField(default=0)),
                ('career_queries', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('satisfaction_rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quercus_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuercusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_user', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(default='gemini-2.5-flash', help_text='Gemini model used for generation', max_length=50)),
                ('tokens_used', models.IntegerField(default=0, help_text='Approximate tokens consumed')),
                ('response_time_ms', models.IntegerField(default=0, help_text='Response time in milliseconds')),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Tokens in the prompt')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Tokens in the completion')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('generation_config', models.JSONField(blank=True, default=dict, help_text='Generation parameters used')),
                ('safety_ratings', models.JSONField(blank=True, default=list, help_text='Gemini safety ratings')),
                ('finish_reason', models.CharField(blank=True, help_text='Reason generation finished', max_length=50)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quercus.quercusconversation')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='quercus_que_convers_443b12_idx'), models.Index(fields=['model_used', 'timestamp'], name='quercus_que_model_u_57edad_idx'), models.Index(fields=['is_user', 'timestamp'], name='quercus_que_is_user_6db838_idx')],
            },
        ),
    ]
