# Generated by Django 5.0.6 on 2025-09-02 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afollows', '0002_initial'),
        ('amessages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagedmessage',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taged_messages_connection', to='afollows.connection'),
        ),
        migrations.AddField(
            model_name='tagedmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taged_message', to='amessages.message'),
        ),
    ]
