# Generated by Django 5.2.8 on 2025-11-24 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ablog', '0001_initial'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='interactions',
            field=models.ManyToManyField(related_name='blog_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloger',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloger',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_name', to='api.communitydirectory'),
        ),
        migrations.AddField(
            model_name='bloger',
            name='shared',
            field=models.ManyToManyField(related_name='shared_interaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloger',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
