# Generated by Django 5.0.6 on 2025-09-02 00:56

import ablog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=ablog.models.upload_post_images)),
                ('description', models.TextField(max_length=1500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
