"""
Django settings for communityapi project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY') # , default='django-insecure-vqf$3qcaae_wp6=%&m20ttc_@)fe!ejffrk!vl&^sh=l)^odw%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',') #, default='127.0.0.1,localhost,192.168.137.1,*.ngrok-free.app'
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

AUTH_USER_MODEL = "api.User"

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)
CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOWED_ORIGINS from environment variable
cors_origins = config('CORS_ALLOWED_ORIGINS') # , default='http://localhost:3000,http://127.0.0.1:3000,http://192.168.137.1:3000'
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',') if origin.strip()]

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


REST_FRAMEWORK = { 
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# Daphne
ASGI_APPLICATION = "communityapi.asgi.application"


# Channels - Redis configuration from environment
REDIS_URL = config('REDIS_URL') # default='redis://196.220.104.115:6379/0

# Parse Redis URL for Channels configuration
from urllib.parse import urlparse
redis_parsed = urlparse(REDIS_URL)
redis_host = redis_parsed.hostname # or '196.220.104.115'
redis_port = redis_parsed.port or 6379
# Use an in-memory channel layer for local development (faster startup, no external Redis required).
# In production (DEBUG=False) we fall back to RedisChannelLayer using REDIS_URL.
if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    (
                        redis_host,
                        redis_port,
                    )
                ],
            },
        },
    }


# Application definition

INSTALLED_APPS = [
     'daphne',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'ablog',
    'afollows',
    'amessages',
    'anotif',
    'api',
    'amonetization',
    'app_notif',
    'asearch',
    'ausernotif',
    'auserpost',
    'community',
    'quercus'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
     "django.contrib.sessions.middleware.SessionMiddleware",
     "corsheaders.middleware.CorsMiddleware",
     "django.middleware.common.CommonMiddleware",
     "django.middleware.csrf.CsrfViewMiddleware",
     "django.contrib.auth.middleware.AuthenticationMiddleware",
     "django.contrib.messages.middleware.MessageMiddleware",
     "django.middleware.clickjacking.XFrameOptionsMiddleware",
     "quercus.middleware.QuercusRateLimitMiddleware",
]

ROOT_URLCONF = 'communityapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'communityapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration from environment
DATABASE_URL = config('DATABASE_URL', default='sqlite:///db.sqlite3')

if DATABASE_URL.startswith('sqlite:///'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / DATABASE_URL.replace('sqlite:///', ''),
        }
    }
else:
    # For other database types (PostgreSQL, MySQL, etc.)
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL)
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Data Media
MEDIA_URL ='media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Gemini AI Settings - Enhanced Configuration
GEMINI_API_KEY = config('GEMINI_API_KEY') # , default='your_gemini_api_key_here

# Gemini API Configuration - Updated for current API version
GEMINI_CONFIG = {
    'DEFAULT_MODEL': 'gemini-2.5-flash',  # Updated to use new model
    'VISION_MODEL': 'gemini-2.5-flash',   # Gemini 2.5 Flash supports vision
    'MAX_RETRIES': 3,
    'TIMEOUT_SECONDS': 30,
    'MAX_TOKENS': 2048,
    'TEMPERATURE': 0.7,
    'TOP_K': 40,
    'TOP_P': 0.95,
}
 
# Safety Settings for Educational Content
GEMINI_SAFETY_SETTINGS = [
    {
        "category": "HARM_CATEGORY_HARASSMENT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        "category": "HARM_CATEGORY_HATE_SPEECH",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    },
    {
        "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE"
    }
]

# Quercus AI Settings - Enhanced
QUERCUS_SETTINGS = {
    'MAX_CONVERSATIONS_PER_USER': 100,
    'MAX_MESSAGES_PER_CONVERSATION': 1000,
    'DEFAULT_RESPONSE_STYLE': 'concise',
    'AI_MODEL_TIMEOUT': 30,
    'ENABLE_CAMPUS_RESOURCES': True,
    'ENABLE_STUDY_PLANS': True,
    'ENABLE_CAREER_GUIDANCE': True,
    'ENABLE_IMAGE_ANALYSIS': True,
    'ENABLE_DOCUMENT_ANALYSIS': True,
    'ENABLE_CONVERSATION_ANALYTICS': True,
    'ENABLE_EXPORT_FEATURES': True,
    'CACHE_TIMEOUT': 300,  # 5 minutes
    'ANALYTICS_RETENTION_DAYS': 90,
}

# Rate Limiting Configuration
QUERCUS_RATE_LIMITS = {
    'AI_GENERATE': {'requests': 20, 'window_minutes': 60},
    'IMAGE_ANALYZE': {'requests': 5, 'window_minutes': 60},
    'DOCUMENT_ANALYZE': {'requests': 10, 'window_minutes': 60},
    'STUDY_PLAN': {'requests': 15, 'window_minutes': 60},
    'CAREER_GUIDANCE': {'requests': 10, 'window_minutes': 60},
    'CONVERSATION_EXPORT': {'requests': 5, 'window_minutes': 60},
}
