# Generated by Django 5.0.6 on 2025-09-02 00:56

import app_notif.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_notif.models.upload_report_images)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attendand', models.ManyToManyField(related_name='app_feedback_attandand', to=settings.AUTH_USER_MODEL)),
                ('red_by', models.ManyToManyField(related_name='app_feedback_red_by', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_feedback_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppNotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_notif.models.upload_post_images)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interactions', models.ManyToManyField(related_name='app_notif_interactions', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ManyToManyField(related_name='app_notif_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notif_sender', to='api.communitydirectory')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notif_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_notif.models.upload_report_images)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attendand', models.ManyToManyField(related_name='app_report_attandand', to=settings.AUTH_USER_MODEL)),
                ('red_by', models.ManyToManyField(related_name='app_report_red_by', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_report_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
