# Generated by Django 5.2.8 on 2025-11-24 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amonetization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='founditem',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_found_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='founditem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='librarymarketing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostfoundmatch',
            name='found_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='amonetization.founditem'),
        ),
        migrations.AddField(
            model_name='lostfoundmatch',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostfoundreward',
            name='found_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='amonetization.founditem'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_lost_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostfoundreward',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='amonetization.lostitem'),
        ),
        migrations.AddField(
            model_name='lostfoundmatch',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='amonetization.lostitem'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='monetizationanalytics',
            index=models.Index(fields=['date', 'page_name'], name='amonetizati_date_62995d_idx'),
        ),
        migrations.AddIndex(
            model_name='monetizationanalytics',
            index=models.Index(fields=['page_name', 'date'], name='amonetizati_page_na_4a078f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monetizationanalytics',
            unique_together={('date', 'page_name')},
        ),
        migrations.AddField(
            model_name='onlinetransaction',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='serviceguide',
            index=models.Index(fields=['service_type', 'is_active'], name='amonetizati_service_116086_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceguide',
            index=models.Index(fields=['is_verified', 'is_active'], name='amonetizati_is_veri_410993_idx'),
        ),
        migrations.AddField(
            model_name='servicedocument',
            name='service_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='amonetization.serviceguide'),
        ),
        migrations.AddField(
            model_name='serviceguideanalytics',
            name='service_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='amonetization.serviceguide'),
        ),
        migrations.AddField(
            model_name='serviceguidesearch',
            name='relevant_documents',
            field=models.ManyToManyField(help_text='Relevant documents found', related_name='searches', to='amonetization.servicedocument'),
        ),
        migrations.AddField(
            model_name='serviceguidesearch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['page_name', 'visited_at'], name='amonetizati_page_na_269a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['user', 'visited_at'], name='amonetizati_user_id_e48850_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedocument',
            index=models.Index(fields=['service_guide', 'is_current'], name='amonetizati_service_663551_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedocument',
            index=models.Index(fields=['is_processed', 'processing_status'], name='amonetizati_is_proc_0d06d5_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceguideanalytics',
            index=models.Index(fields=['service_guide', 'date'], name='amonetizati_service_cb4ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceguideanalytics',
            index=models.Index(fields=['date', 'views'], name='amonetizati_date_4ed600_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceguideanalytics',
            unique_together={('service_guide', 'date')},
        ),
        migrations.AddIndex(
            model_name='serviceguidesearch',
            index=models.Index(fields=['created_at'], name='amonetizati_created_3c3d49_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceguidesearch',
            index=models.Index(fields=['user', 'created_at'], name='amonetizati_user_id_b92d9f_idx'),
        ),
    ]
