# Generated by Django 5.0.6 on 2025-09-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonetization', '0002_paymentwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('images', models.JSONField(blank=True, default=list)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lng', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('inquiries', models.IntegerField(default=0)),
                ('virtual_views', models.IntegerField(default=0)),
                ('verify_badge', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
