# Generated by Django 5.0.6 on 2025-09-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonetization', '0003_accommodation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='owner',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
