# Generated by Django 5.0.6 on 2025-09-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amonetization', '0005_campusmap_librarymarketing_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinetransaction',
            name='contact_phone',
        ),
    ]
