# Generated by Django 5.0.6 on 2025-09-23 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonetization', '0007_founditem_lostitem_lostfoundreward_lostfoundmatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(help_text='e.g., Academic, Administrative, Student Services', max_length=100)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(help_text='Brief description of the service')),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours by day')),
                ('website_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('search_keywords', models.JSONField(blank=True, default=list, help_text='Keywords for AI search')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['service_type', 'is_active'], name='amonetizati_service_116086_idx'), models.Index(fields=['is_verified', 'is_active'], name='amonetizati_is_veri_410993_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('document_file', models.FileField(help_text='PDF document', upload_to='service_guides/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether document has been processed for AI search')),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text content for AI search')),
                ('processing_status', models.CharField(default='pending', help_text='Document processing status', max_length=50)),
                ('version', models.CharField(default='1.0', help_text='Document version', max_length=50)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current version')),
                ('uploaded_via_email', models.BooleanField(default=False, help_text='Whether uploaded via email')),
                ('email_message_id', models.CharField(blank=True, help_text='Email message ID if uploaded via email', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='amonetization.serviceguide')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGuideAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('searches', models.IntegerField(default=0)),
                ('document_downloads', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('avg_confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='amonetization.serviceguide')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGuideSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='User search query')),
                ('response', models.TextField(help_text='AI generated response')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in response')),
                ('search_metadata', models.JSONField(blank=True, default=dict, help_text='Additional search metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relevant_documents', models.ManyToManyField(help_text='Relevant documents found', related_name='searches', to='amonetization.servicedocument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='servicedocument',
            index=models.Index(fields=['service_guide', 'is_current'], name='amonetizati_service_663551_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedocument',
            index=models.Index(fields=['is_processed', 'processing_status'], name='amonetizati_is_proc_0d06d5_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceguideanalytics',
            index=models.Index(fields=['service_guide', 'date'], name='amonetizati_service_cb4ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceguideanalytics',
            index=models.Index(fields=['date', 'views'], name='amonetizati_date_4ed600_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceguideanalytics',
            unique_together={('service_guide', 'date')},
        ),
        migrations.AddIndex(
            model_name='serviceguidesearch',
            index=models.Index(fields=['created_at'], name='amonetizati_created_3c3d49_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceguidesearch',
            index=models.Index(fields=['user', 'created_at'], name='amonetizati_user_id_b92d9f_idx'),
        ),
    ]
