# Generated by Django 5.0.6 on 2025-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonetization', '0008_serviceguide_servicedocument_serviceguideanalytics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedocument',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
